  # Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip
    displayName: 'Upgrade pip'

  - script: python -m pip install chameleon
    displayName: 'Install Chameleon'

  - script: python -m pip install markdown
    displayName: 'Install Markdown'

  - script: python -m pip install nml
    displayName: 'Install NML'

  - script: python -m pip install ply
    displayName: 'Install PLY'

  - script: python -m pip install pillow
    displayName: 'Install Pillow'

  - script: make
    displayName: 'Make'

- task: AccidentalFish.githubpages-publish.AccidentalFish.GitHubPages-Publish.GitHubPagesPublish@0
    displayName: 'Publishes to GitHub Pages'
    inputs:
        githubusername: andythenorth
        githubaccesstoken: b8fc99f59f646df4426238f87f16488b3803f219
        repositoryname: firs
        PathtoPublish: docs
        ArtifactName: 'docs'
